theme: jekyll-theme-minimal
title: ASI Saga
description: The ASI Saga encompasses the journey from the inception of AI to the creation and integration of superintelligent systems that surpass human cognitive abilities.
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
